// Generated by CoffeeScript 1.7.1
(function() {
  var array, x, _i, _len;

  array = ["x", "x", "y"];

  for (_i = 0, _len = array.length; _i < _len; _i++) {
    x = array[_i];
    $.inArray("x", array[i]);
    i++;
  }

}).call(this);

//# sourceMappingURL=test.map
